version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    environment:
      - BACKEND_PORT=5000

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
